@ApiService_HostAddress = http://localhost:5321
@AuthApiService_HostAddress = http://localhost:51895

### 1. Authenticate default seeded user and get a JWT token
# @name login
POST {{AuthApiService_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "nordyn@hotmail.fr",
  "password": "Aqw1!"
}

### 2. Search a card with the name "Black Lotus"
GET {{ApiService_HostAddress}}/api/cards/search?q=Black%20Lotus
Accept: application/json

### 3. Advanced search
POST {{ApiService_HostAddress}}/api/cards/search/advanced
Content-Type: application/json
Accept: application/json

{
  "types": ["elf"],
  "manaCost": "G",
  "manaValue": 3,
  "PageSize" : 10
}

### 4. Call API with JWT - TEST 200
GET {{ApiService_HostAddress}}/api/user/private
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

### 5. Call API without JWT - TEST 401
GET {{ApiService_HostAddress}}/api/user/private
Accept: application/json

### 6. Test auth api
GET {{AuthApiService_HostAddress}}/api/auth/me
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}