@ApiService_HostAddress = http://localhost:5321

GET {{ApiService_HostAddress}}/weatherforecast/
Accept: application/json

### Search a card with the name "Black Lotus" using simple query parameters
GET {{ApiService_HostAddress}}/api/cards/search?q=Black%20Lotus
Accept: application/json

### Search a card with the name "Elf", mana cost equal to 1 using advanced query parameters
POST {{ApiService_HostAddress}}/api/cards/search/advanced
Content-Type: application/json
Accept: application/json

{
  "types": ["elf"], "manaCost": "G", "manaValue": 3
}